"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Callable, Dict, Generator, TYPE_CHECKING, Union, cast
from twisted.internet import defer
from twisted.internet.defer import Deferred
from scrapy import Request, Spider, signals
from scrapy.exceptions import NotConfigured, NotSupported
from scrapy.utils.httpobj import urlparse_cached
from scrapy.utils.misc import create_instance, load_object
from scrapy.utils.python import without_none_values
from scrapy.crawler import Crawler

"""Download handlers for different schemes"""
if TYPE_CHECKING:
    ...
logger = ...
class DownloadHandlers:
    def __init__(self, crawler: Crawler) -> None:
        ...
    
    def download_request(self, request: Request, spider: Spider) -> Deferred:
        ...
    


