"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Union
from twisted.internet.defer import Deferred
from twisted.python.failure import Failure
from scrapy import Request, Spider
from scrapy.http import Response
from scrapy.middleware import MiddlewareManager

"""
Spider Middleware manager

See documentation in docs/topics/spider-middleware.rst
"""
logger = ...
ScrapeFunc = Callable[[Union[Response, Failure], Request, Spider], Any]
class SpiderMiddlewareManager(MiddlewareManager):
    component_name = ...
    def __init__(self, *middlewares) -> None:
        ...
    
    def scrape_response(self, scrape_func: ScrapeFunc, response: Response, request: Request, spider: Spider) -> Deferred:
        ...
    
    def process_start_requests(self, start_requests, spider: Spider) -> Deferred:
        ...
    


