"""
This type stub file was generated by pyright.
"""

"""Common functions used in Item Loaders code"""
def wrap_loader_context(function, context):
    """Wrap functions that receive loader_context to contain the context
    "pre-loaded" and expose a interface that receives only one argument
    """
    ...

