"""
This type stub file was generated by pyright.
"""

from scrapy.utils.datatypes import CaselessDict

class Headers(CaselessDict):
    """Case insensitive http headers dictionary"""
    def __init__(self, seq=..., encoding=...) -> None:
        ...
    
    def update(self, seq): # -> None:
        ...
    
    def normkey(self, key): # -> bytes:
        """Normalize key to bytes"""
        ...
    
    def normvalue(self, value): # -> list[bytes]:
        """Normalize values to bytes"""
        ...
    
    def __getitem__(self, key): # -> None:
        ...
    
    def get(self, key, def_val=...): # -> None:
        ...
    
    def getlist(self, key, def_val=...): # -> list[bytes] | list[Unknown]:
        ...
    
    def setlist(self, key, list_): # -> None:
        ...
    
    def setlistdefault(self, key, default_list=...): # -> None:
        ...
    
    def appendlist(self, key, value): # -> None:
        ...
    
    def items(self): # -> Generator[tuple[Unknown, Unknown | list[bytes] | list[Unknown]], None, None]:
        ...
    
    def values(self): # -> list[Unknown | None]:
        ...
    
    def to_string(self): # -> bytes | None:
        ...
    
    def to_unicode_dict(self): # -> CaselessDict:
        """ Return headers as a CaselessDict with unicode keys
        and unicode values. Multiple values are joined with ','.
        """
        ...
    
    def __copy__(self): # -> Headers:
        ...
    
    copy = ...


