"""
This type stub file was generated by pyright.
"""

from scrapy.utils.datatypes import CaselessDict
from typing import Any, Optional

class Headers(CaselessDict):
    """Case insensitive http headers dictionary"""
    def __init__(self, seq: Optional[Any] = ..., encoding=...):
        self.encoding = ...
    
    def normkey(self, key):
        """Normalize key to bytes"""
        ...
    
    def normvalue(self, value):
        """Normalize values to bytes"""
        ...
    
    def _tobytes(self, x):
        ...
    
    def __getitem__(self, key):
        ...
    
    def get(self, key, def_val: Optional[Any] = ...):
        ...
    
    def getlist(self, key, def_val: Optional[Any] = ...):
        ...
    
    def setlist(self, key, list_):
        ...
    
    def setlistdefault(self, key, default_list=...):
        ...
    
    def appendlist(self, key, value):
        ...
    
    def items(self):
        ...
    
    def iteritems(self):
        ...
    
    def values(self):
        ...
    
    def to_string(self):
        ...
    
    def to_unicode_dict(self):
        """ Return headers as a CaselessDict with unicode keys
        and unicode values. Multiple values are joined with ','.
        """
        ...
    
    def __copy__(self):
        ...
    
    copy = ...


