"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from scrapy.settings import Settings
from scrapy.crawler import Crawler

if TYPE_CHECKING:
    ...
logger = ...
class AddonManager:
    """This class facilitates loading and storing :ref:`topics-addons`."""
    def __init__(self, crawler: Crawler) -> None:
        ...
    
    def load_settings(self, settings: Settings) -> None:
        """Load add-ons and configurations from a settings object and apply them.

        This will load the add-on for every add-on path in the
        ``ADDONS`` setting and execute their ``update_settings`` methods.

        :param settings: The :class:`~scrapy.settings.Settings` object from \
            which to read the add-on configuration
        :type settings: :class:`~scrapy.settings.Settings`
        """
        ...
    


