"""
This type stub file was generated by pyright.
"""

import argparse

class ScrapyArgumentParser(argparse.ArgumentParser):
    ...


def execute(argv=..., settings=...):
    ...

if __name__ == '__main__':
    ...
