"""
This type stub file was generated by pyright.
"""

from scrapy.middleware import MiddlewareManager

"""
The Extension Manager

See documentation in docs/topics/extensions.rst
"""
class ExtensionManager(MiddlewareManager):
    component_name = ...
    @classmethod
    def _get_mwlist_from_settings(cls, settings):
        ...
    


