"""
This type stub file was generated by pyright.
"""

from zope.interface import Interface

class ISpiderLoader(Interface):
    def from_settings(settings): # -> None:
        """Return an instance of the class for the given settings"""
        ...
    
    def load(spider_name): # -> None:
        """Return the Spider class for the given spider name. If the spider
        name is not found, it must raise a KeyError."""
        ...
    
    def list(): # -> None:
        """Return a list with the names of all spiders available in the
        project"""
        ...
    
    def find_by_request(request): # -> None:
        """Return the list of spiders names that can handle the given request"""
        ...
    


