"""
This type stub file was generated by pyright.
"""

"""
Mail sending helpers

See documentation in docs/topics/email.rst
"""
logger = ...
COMMASPACE = ...
class MailSender:
    def __init__(self, smtphost=..., mailfrom=..., smtpuser=..., smtppass=..., smtpport=..., smtptls=..., smtpssl=..., debug=...) -> None:
        ...
    
    @classmethod
    def from_settings(cls, settings): # -> Self:
        ...
    
    def send(self, to, subject, body, cc=..., attachs=..., mimetype=..., charset=..., _callback=...): # -> Deferred[Any] | None:
        ...
    


