"""
This type stub file was generated by pyright.
"""

from twisted.internet.defer import Deferred
from scrapy import Spider
from scrapy.settings import Settings

logger = ...
class MiddlewareManager:
    """Base class for implementing middleware managers"""
    component_name = ...
    def __init__(self, *middlewares) -> None:
        ...
    
    @classmethod
    def from_settings(cls, settings: Settings, crawler=...): # -> Self@MiddlewareManager:
        ...
    
    @classmethod
    def from_crawler(cls, crawler): # -> Self@MiddlewareManager:
        ...
    
    def open_spider(self, spider: Spider) -> Deferred:
        ...
    
    def close_spider(self, spider: Spider) -> Deferred:
        ...
    


