"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, TYPE_CHECKING
from twisted.internet.defer import Deferred
from scrapy import Spider
from scrapy.settings import Settings
from typing_extensions import Self
from scrapy.crawler import Crawler

if TYPE_CHECKING:
    ...
logger = ...
class MiddlewareManager:
    """Base class for implementing middleware managers"""
    component_name = ...
    def __init__(self, *middlewares: Any) -> None:
        ...
    
    @classmethod
    def from_settings(cls, settings: Settings, crawler: Optional[Crawler] = ...) -> Self:
        ...
    
    @classmethod
    def from_crawler(cls, crawler: Crawler) -> Self:
        ...
    
    def open_spider(self, spider: Spider) -> Deferred:
        ...
    
    def close_spider(self, spider: Spider) -> Deferred:
        ...
    


