"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

"""
This module implements a class which returns the appropriate Response class
based on different criteria.
"""
class ResponseTypes(object):
    CLASSES = ...
    def __init__(self):
        self.classes = ...
        self.mimetypes = ...
    
    def from_mimetype(self, mimetype):
        """Return the most appropriate Response class for the given mimetype"""
        ...
    
    def from_content_type(self, content_type, content_encoding: Optional[Any] = ...):
        """Return the most appropriate Response class from an HTTP Content-Type
        header """
        ...
    
    def from_content_disposition(self, content_disposition):
        ...
    
    def from_headers(self, headers):
        """Return the most appropriate Response class by looking at the HTTP
        headers"""
        ...
    
    def from_filename(self, filename):
        """Return the most appropriate Response class from a file name"""
        ...
    
    def from_body(self, body):
        """Try to guess the appropriate response based on the body content.
        This method is a bit magic and could be improved in the future, but
        it's not meant to be used except for special cases where response types
        cannot be guess using more straightforward methods."""
        ...
    
    def from_args(self, headers: Optional[Any] = ..., url: Optional[Any] = ..., filename: Optional[Any] = ..., body: Optional[Any] = ...):
        """Guess the most appropriate Response class based on
        the given arguments."""
        ...
    


responsetypes = ResponseTypes()
