"""
This type stub file was generated by pyright.
"""

import logging
from abc import ABCMeta, abstractmethod
from six import with_metaclass

logger = logging.getLogger(__name__)
def decode_robotstxt(robotstxt_body, spider, to_native_str_type: bool = ...):
    ...

class RobotParser(with_metaclass(ABCMeta)):
    @classmethod
    @abstractmethod
    def from_crawler(cls, crawler, robotstxt_body):
        """Parse the content of a robots.txt_ file as bytes. This must be a class method.
        It must return a new instance of the parser backend.

        :param crawler: crawler which made the request
        :type crawler: :class:`~scrapy.crawler.Crawler` instance

        :param robotstxt_body: content of a robots.txt_ file.
        :type robotstxt_body: bytes
        """
        ...
    
    @abstractmethod
    def allowed(self, url, user_agent):
        """Return ``True`` if  ``user_agent`` is allowed to crawl ``url``, otherwise return ``False``.

        :param url: Absolute URL
        :type url: string

        :param user_agent: User agent
        :type user_agent: string
        """
        ...
    


class PythonRobotParser(RobotParser):
    def __init__(self, robotstxt_body, spider):
        self.spider = ...
        self.rp = ...
    
    @classmethod
    def from_crawler(cls, crawler, robotstxt_body):
        ...
    
    def allowed(self, url, user_agent):
        ...
    


class ReppyRobotParser(RobotParser):
    def __init__(self, robotstxt_body, spider):
        self.spider = ...
        self.rp = ...
    
    @classmethod
    def from_crawler(cls, crawler, robotstxt_body):
        ...
    
    def allowed(self, url, user_agent):
        ...
    


class RerpRobotParser(RobotParser):
    def __init__(self, robotstxt_body, spider):
        self.spider = ...
        self.rp = ...
    
    @classmethod
    def from_crawler(cls, crawler, robotstxt_body):
        ...
    
    def allowed(self, url, user_agent):
        ...
    


class ProtegoRobotParser(RobotParser):
    def __init__(self, robotstxt_body, spider):
        self.spider = ...
        self.rp = ...
    
    @classmethod
    def from_crawler(cls, crawler, robotstxt_body):
        ...
    
    def allowed(self, url, user_agent):
        ...
    


