"""
This type stub file was generated by pyright.
"""

"""Scrapy Shell

See documentation in docs/topics/shell.rst

"""
class Shell:
    relevant_classes = ...
    def __init__(self, crawler, update_vars=..., code=...) -> None:
        ...
    
    def start(self, url=..., request=..., response=..., spider=..., redirect=...): # -> None:
        ...
    
    def fetch(self, request_or_url, spider=..., redirect=..., **kwargs): # -> None:
        ...
    
    def populate_vars(self, response=..., request=..., spider=...): # -> None:
        ...
    
    def print_help(self): # -> None:
        ...
    
    def get_help(self): # -> str:
        ...
    


def inspect_response(response, spider): # -> None:
    """Open a shell to inspect the given response"""
    ...

