"""
This type stub file was generated by pyright.
"""

from typing import List, TYPE_CHECKING, Type
from zope.interface import implementer
from scrapy import Request, Spider
from scrapy.interfaces import ISpiderLoader
from scrapy.settings import BaseSettings
from typing_extensions import Self

if TYPE_CHECKING:
    ...
@implementer(ISpiderLoader)
class SpiderLoader:
    """
    SpiderLoader is a class which locates and loads spiders
    in a Scrapy project.
    """
    def __init__(self, settings: BaseSettings) -> None:
        ...
    
    @classmethod
    def from_settings(cls, settings: BaseSettings) -> Self:
        ...
    
    def load(self, spider_name: str) -> Type[Spider]:
        """
        Return the Spider class for the given spider name. If the spider
        name is not found, raise a KeyError.
        """
        ...
    
    def find_by_request(self, request: Request) -> List[str]:
        """
        Return the list of spider names that can handle the given request.
        """
        ...
    
    def list(self) -> List[str]:
        """
        Return a list with the names of all spiders available in the project.
        """
        ...
    


