"""
This type stub file was generated by pyright.
"""

from zope.interface import implementer
from scrapy.interfaces import ISpiderLoader

@implementer(ISpiderLoader)
class SpiderLoader(object):
    """
    SpiderLoader is a class which locates and loads spiders
    in a Scrapy project.
    """
    def __init__(self, settings):
        self.spider_modules = ...
        self.warn_only = ...
    
    def _check_name_duplicates(self):
        ...
    
    def _load_spiders(self, module):
        ...
    
    def _load_all_spiders(self):
        ...
    
    @classmethod
    def from_settings(cls, settings):
        ...
    
    def load(self, spider_name):
        """
        Return the Spider class for the given spider name. If the spider
        name is not found, raise a KeyError.
        """
        ...
    
    def find_by_request(self, request):
        """
        Return the list of spider names that can handle the given request.
        """
        ...
    
    def list(self):
        """
        Return a list with the names of all spiders available in the project.
        """
        ...
    


