"""
This type stub file was generated by pyright.
"""

from zope.interface import implementer
from scrapy.interfaces import ISpiderLoader

@implementer(ISpiderLoader)
class SpiderLoader:
    """
    SpiderLoader is a class which locates and loads spiders
    in a Scrapy project.
    """
    def __init__(self, settings) -> None:
        ...
    
    @classmethod
    def from_settings(cls, settings): # -> Self@SpiderLoader:
        ...
    
    def load(self, spider_name):
        """
        Return the Spider class for the given spider name. If the spider
        name is not found, raise a KeyError.
        """
        ...
    
    def find_by_request(self, request): # -> list[Unknown]:
        """
        Return the list of spider names that can handle the given request.
        """
        ...
    
    def list(self): # -> list[Unknown]:
        """
        Return a list with the names of all spiders available in the project.
        """
        ...
    


