"""
This type stub file was generated by pyright.
"""

import logging
from .config import VCR
from logging import NullHandler
from .record_mode import RecordMode as mode

__version__ = ...
default_vcr = ...
use_cassette = ...
