"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class VCR:
    @staticmethod
    def is_test_method(method_name, function):
        ...
    
    @staticmethod
    def ensure_suffix(suffix):
        ...
    
    def __init__(self, path_transformer=..., before_record_request=..., custom_patches=..., filter_query_parameters=..., ignore_hosts=..., record_mode=..., ignore_localhost=..., filter_headers=..., before_record_response=..., filter_post_data_parameters=..., match_on=..., before_record=..., inject_cassette=..., serializer=..., cassette_library_dir=..., func_path_generator=..., decode_compressed_response=...) -> None:
        ...
    
    def use_cassette(self, path=..., **kwargs):
        ...
    
    def get_merged_config(self, **kwargs):
        ...
    
    def register_serializer(self, name, serializer):
        ...
    
    def register_matcher(self, name, matcher):
        ...
    
    def register_persister(self, persister):
        ...
    
    def test_case(self, predicate=...):
        ...
    


