"""
This type stub file was generated by pyright.
"""

class CannotOverwriteExistingCassetteException(Exception):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class UnhandledHTTPRequestError(KeyError):
    """Raised when a cassette does not contain the request we want."""
    ...


