"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
log = ...
def method(r1, r2):
    ...

def uri(r1, r2):
    ...

def host(r1, r2):
    ...

def scheme(r1, r2):
    ...

def port(r1, r2):
    ...

def path(r1, r2):
    ...

def query(r1, r2):
    ...

def raw_body(r1, r2):
    ...

def body(r1, r2):
    ...

def headers(r1, r2):
    ...

_xml_header_checker = ...
_xmlrpc_header_checker = ...
_checker_transformer_pairs = ...
def requests_match(r1, r2, matchers):
    ...

def get_matchers_results(r1, r2, matchers):
    """
    Get the comparison results of two requests as two list.
    The first returned list represents the matchers names that passed.
    The second list is the failed matchers as a string with failed assertion details if any.
    """
    ...

def get_assertion_message(assertion_details):
    """
    Get a detailed message about the failing matcher.
    """
    ...

