"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def preprocess_yaml(cassette):
    ...

PARTS = ...
def build_uri(**parts):
    ...

def migrate_json(in_fp, out_fp):
    ...

def migrate_yml(in_fp, out_fp):
    ...

def migrate(file_path, migration_fn):
    ...

def try_migrate(path):
    ...

def main():
    ...

if __name__ == "__main__":
    ...
