"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
CASSETTE_FORMAT_VERSION = ...
def deserialize(cassette_string, serializer):
    ...

def serialize(cassette_dict, serializer):
    ...

