"""
This type stub file was generated by pyright.
"""

class Result:
    def __init__(self, score, grade_levels) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class DaleChall:
    def __init__(self, stats) -> None:
        ...
    
    def score(self): # -> Result:
        ...
    


