"""
This type stub file was generated by pyright.
"""

class Result:
    def __init__(self, score, grade_level) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class Smog:
    def __init__(self, stats, sentences, all_sentences=...) -> None:
        """
        Computes the SMOG readability score (Harry McLaughlin, 1969 https://ogg.osu.edu/media/documents/health_lit/WRRSMOG_Readability_Formula_G._Harry_McLaughlin__1969_.pdf)
        If all_sentences is false, computes the score as described in McLaughlin, 1969, using exactly 30 sentences
        If all_sentences is true, adjusts the score to use all sentences in the text
        """
        ...
    
    def score(self): # -> Result:
        ...
    


