"""
This type stub file was generated by pyright.
"""

import re
from urllib.parse import urlparse
from warnings import warn
from parsel.csstranslator import HTMLTranslator
from w3lib.url import canonicalize_url
from scrapy.utils.deprecate import ScrapyDeprecationWarning
from scrapy.utils.misc import arg_to_iter
from scrapy.utils.url import url_has_any_extension, url_is_from_any_domain
from scrapy.linkextractors.lxmlhtml import LxmlLinkExtractor as LinkExtractor

"""
scrapy.linkextractors

This package contains a collection of Link Extractors.

For more info see docs/topics/link-extractors.rst
"""
IGNORED_EXTENSIONS = ...
_re_type = ...
class FilteringLinkExtractor:
    _csstranslator = ...
    def __new__(cls, *args, **kwargs): # -> FilteringLinkExtractor | LxmlLinkExtractor:
        ...
    
    def __init__(self, link_extractor, allow, deny, allow_domains, deny_domains, restrict_xpaths, canonicalize, deny_extensions, restrict_css, restrict_text) -> None:
        ...
    
    def matches(self, url): # -> bool:
        ...
    


