"""
This type stub file was generated by pyright.
"""

import re
from scrapy.linkextractors.lxmlhtml import LxmlLinkExtractor as LinkExtractor

"""
scrapy.linkextractors

This package contains a collection of Link Extractors.

For more info see docs/topics/link-extractors.rst
"""
IGNORED_EXTENSIONS = ...
_re_type = ...
