"""
This type stub file was generated by pyright.
"""

from scrapy.linkextractors import FilteringLinkExtractor

"""
Link extractor based on lxml.html
"""
XHTML_NAMESPACE = ...
_collect_string_content = ...
class LxmlParserLinkExtractor:
    def __init__(self, tag=..., attr=..., process=..., unique=..., strip=..., canonicalized=...) -> None:
        ...
    
    def extract_links(self, response): # -> list[Unknown]:
        ...
    


class LxmlLinkExtractor(FilteringLinkExtractor):
    def __init__(self, allow=..., deny=..., allow_domains=..., deny_domains=..., restrict_xpaths=..., tags=..., attrs=..., canonicalize=..., unique=..., process_value=..., deny_extensions=..., restrict_css=..., strip=..., restrict_text=...) -> None:
        ...
    
    def extract_links(self, response): # -> list[Unknown]:
        """Returns a list of :class:`~scrapy.link.Link` objects from the
        specified :class:`response <scrapy.http.Response>`.

        Only links that match the settings passed to the ``__init__`` method of
        the link extractor are returned.

        Duplicate links are omitted.
        """
        ...
    


