"""
This type stub file was generated by pyright.
"""

import random
from collections import deque
from datetime import datetime
from time import time
from typing import Any, Deque, Dict, Set, TYPE_CHECKING, Tuple, cast
from twisted.internet import task
from twisted.internet.defer import Deferred
from scrapy import Request, Spider, signals
from scrapy.core.downloader.handlers import DownloadHandlers
from scrapy.core.downloader.middleware import DownloaderMiddlewareManager
from scrapy.http import Response
from scrapy.resolver import dnscache
from scrapy.settings import BaseSettings
from scrapy.signalmanager import SignalManager
from scrapy.utils.defer import mustbe_deferred
from scrapy.utils.httpobj import urlparse_cached
from scrapy.crawler import Crawler

if TYPE_CHECKING:
    ...
class Slot:
    """Downloader slot"""
    def __init__(self, concurrency: int, delay: float, randomize_delay: bool) -> None:
        ...
    
    def free_transfer_slots(self) -> int:
        ...
    
    def download_delay(self) -> float:
        ...
    
    def close(self) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


class Downloader:
    DOWNLOAD_SLOT = ...
    def __init__(self, crawler: Crawler) -> None:
        ...
    
    def fetch(self, request: Request, spider: Spider) -> Deferred:
        ...
    
    def needs_backout(self) -> bool:
        ...
    
    def close(self) -> None:
        ...
    


