"""
This type stub file was generated by pyright.
"""

from typing import Callable
from twisted.internet.defer import Deferred
from scrapy import Spider
from scrapy.http import Request
from scrapy.middleware import MiddlewareManager

"""
Downloader Middleware manager

See documentation in docs/topics/downloader-middleware.rst
"""
class DownloaderMiddlewareManager(MiddlewareManager):
    component_name = ...
    def download(self, download_func: Callable, request: Request, spider: Spider) -> Deferred:
        ...
    


