"""
This type stub file was generated by pyright.
"""

from .timer import Timer
from typing import Any, List, Optional

__all__ = ('Debug', 'debug')
MYPY = ...
if MYPY:
    ...
pformat = ...
class DebugArgument:
    __slots__ = ...
    def __init__(self, value, *, name=..., **extra) -> None:
        ...
    
    def str(self, highlight=...) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


class DebugOutput:
    """
    Represents the output of a debug command.
    """
    arg_class = DebugArgument
    __slots__ = ...
    def __init__(self, *, filename: str, lineno: int, frame: str, arguments: List[DebugArgument], warning=...) -> None:
        ...
    
    def str(self, highlight=...) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


class Debug:
    output_class = DebugOutput
    def __init__(self, *, warnings: Optional[bool] = ..., highlight: Optional[bool] = ...) -> None:
        ...
    
    def __call__(self, *args, file_=..., flush_=..., **kwargs) -> Any:
        ...
    
    def format(self, *args, **kwargs) -> DebugOutput:
        ...
    
    def breakpoint(self): # -> None:
        ...
    
    def timer(self, name=..., *, verbose=..., file=..., dp=...) -> Timer:
        ...
    


debug = ...
