"""
This type stub file was generated by pyright.
"""

__all__ = ('Timer', )
class TimerResult:
    def __init__(self, name=..., verbose=...) -> None:
        ...
    
    def capture(self): # -> None:
        ...
    
    def elapsed(self): # -> float | Literal[-1]:
        ...
    
    def str(self, dp=...): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


_SUMMARY_TEMPLATE = ...
class Timer:
    def __init__(self, name=..., verbose=..., file=..., dp=...) -> None:
        ...
    
    def __call__(self, name=..., verbose=...): # -> Self@Timer:
        ...
    
    def start(self, name=..., verbose=...): # -> Self@Timer:
        ...
    
    def capture(self, verbose=...):
        ...
    
    def summary(self, verbose=...): # -> set[Unknown]:
        ...
    
    def __enter__(self): # -> Self@Timer:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


