"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

__all__ = ('isatty', 'env_true', 'env_bool', 'use_highlight', 'is_literal', 'LaxMapping', 'DataClassType', 'SQLAlchemyClassType')
MYPY = ...
if MYPY:
    ...
def isatty(stream=...): # -> bool:
    ...

def env_true(var_name: str, alt: Optional[bool] = ...) -> Optional[bool]:
    ...

def env_bool(value: Optional[bool], env_name: str, env_default: Optional[bool]) -> Optional[bool]:
    ...

def activate_win_color() -> bool:
    """
    Activate ANSI support on windows consoles.

    As of Windows 10, the windows conolse got some support for ANSI escape
    sequences. Unfortunately it has to be enabled first using `SetConsoleMode`.
    See: https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

    Code snippet source: https://bugs.python.org/msg291732
    """
    ...

def use_highlight(highlight: Optional[bool] = ..., file_=...) -> bool:
    ...

def is_literal(s): # -> bool:
    ...

class MetaLaxMapping(type):
    def __instancecheck__(self, instance: Any) -> bool:
        ...
    


class LaxMapping(metaclass=MetaLaxMapping):
    ...


class MetaDataClassType(type):
    def __instancecheck__(self, instance: Any) -> bool:
        ...
    


class DataClassType(metaclass=MetaDataClassType):
    ...


class MetaSQLAlchemyClassType(type):
    def __instancecheck__(self, instance: Any) -> bool:
        ...
    


class SQLAlchemyClassType(metaclass=MetaSQLAlchemyClassType):
    ...


