"""
This type stub file was generated by pyright.
"""

class Readability:
    def __init__(self, text) -> None:
        ...
    
    def ari(self): # -> Result:
        """Calculate Automated Readability Index (ARI)."""
        ...
    
    def coleman_liau(self): # -> Result:
        """Calculate Coleman Liau Index."""
        ...
    
    def dale_chall(self): # -> Result:
        """Calculate Dale Chall."""
        ...
    
    def flesch(self): # -> Result:
        """Calculate Flesch Reading Ease score."""
        ...
    
    def flesch_kincaid(self): # -> Result:
        """Calculate Flesch-Kincaid Grade Level."""
        ...
    
    def gunning_fog(self): # -> Result:
        """Calculate Gunning Fog score."""
        ...
    
    def linsear_write(self): # -> Result:
        """Calculate Linsear Write."""
        ...
    
    def smog(self, all_sentences=...): # -> Result:
        """SMOG Index.
        `all_sentences` indicates whether SMOG should use a sample of 30 sentences, as described in the original paper, or if it should use all sentences in the text"""
        ...
    
    def spache(self): # -> Result:
        """Spache Index."""
        ...
    
    def statistics(self): # -> dict[str, Unknown]:
        ...
    


