"""
This type stub file was generated by pyright.
"""

import logging
import warnings
from scrapy import signals
from scrapy.http import Request
from scrapy.utils.trackref import object_ref
from scrapy.utils.url import url_is_from_spider
from scrapy.exceptions import ScrapyDeprecationWarning
from scrapy.utils.deprecate import method_is_overridden
from typing import Any, Optional
from scrapy.spiders.crawl import CrawlSpider, Rule
from scrapy.spiders.feed import CSVFeedSpider, XMLFeedSpider
from scrapy.spiders.sitemap import SitemapSpider

"""
Base class for Scrapy spiders

See documentation in docs/topics/spiders.rst
"""
class Spider(object_ref):
    """Base class for scrapy spiders. All spiders must inherit from this
    class.
    """
    name = ...
    custom_settings = ...
    def __init__(self, name: Optional[Any] = ..., **kwargs):
        ...
    
    @property
    def logger(self):
        ...
    
    def log(self, message, level=..., **kw):
        """Log the given message at the given log level

        This helper wraps a log call to the logger within the spider, but you
        can use it directly (e.g. Spider.logger.info('msg')) or use any other
        Python logger too.
        """
        ...
    
    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        ...
    
    def _set_crawler(self, crawler):
        self.crawler = ...
        self.settings = ...
    
    def start_requests(self):
        ...
    
    def make_requests_from_url(self, url):
        """ This method is deprecated. """
        ...
    
    def parse(self, response):
        ...
    
    @classmethod
    def update_settings(cls, settings):
        ...
    
    @classmethod
    def handles_request(cls, request):
        ...
    
    @staticmethod
    def close(spider, reason):
        ...
    
    def __str__(self):
        ...
    
    __repr__ = ...


