"""
This type stub file was generated by pyright.
"""

from typing import Sequence
from scrapy.http import Response
from scrapy.spiders import Spider

"""
This modules implements the CrawlSpider which is the recommended spider to use
for scraping typical web sites that requires crawling pages.

See documentation in docs/topics/spiders.rst
"""
_default_link_extractor = ...
class Rule:
    def __init__(self, link_extractor=..., callback=..., cb_kwargs=..., follow=..., process_links=..., process_request=..., errback=...) -> None:
        ...
    


class CrawlSpider(Spider):
    rules: Sequence[Rule] = ...
    def __init__(self, *a, **kw) -> None:
        ...
    
    def parse_start_url(self, response, **kwargs): # -> list[Unknown]:
        ...
    
    def process_results(self, response: Response, results: list): # -> list[Unknown]:
        ...
    
    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs): # -> Self@CrawlSpider:
        ...
    


