"""
This type stub file was generated by pyright.
"""

import logging
from scrapy.spiders import Spider

logger = logging.getLogger(__name__)
class SitemapSpider(Spider):
    sitemap_urls = ...
    sitemap_rules = ...
    sitemap_follow = ...
    sitemap_alternate_links = ...
    def __init__(self, *a, **kw):
        ...
    
    def start_requests(self):
        ...
    
    def sitemap_filter(self, entries):
        """This method can be used to filter sitemap entries by their
        attributes, for example, you can filter locs with lastmod greater
        than a given date (see docs).
        """
        ...
    
    def _parse_sitemap(self, response):
        ...
    
    def _get_sitemap_body(self, response):
        """Return the sitemap body contained in the given response,
        or None if the response is not a sitemap.
        """
        ...
    


def regex(x):
    ...

def iterloc(it, alt: bool = ...):
    ...

