"""
This type stub file was generated by pyright.
"""

class AnalyzerStatistics:
    def __init__(self, stats) -> None:
        ...
    
    @property
    def num_poly_syllable_words(self):
        ...
    
    @property
    def num_syllables(self):
        ...
    
    @property
    def num_letters(self):
        ...
    
    @property
    def num_words(self):
        ...
    
    @property
    def num_sentences(self):
        ...
    
    @property
    def num_gunning_complex(self):
        ...
    
    @property
    def num_dale_chall_complex(self):
        ...
    
    @property
    def num_spache_complex(self):
        ...
    
    @property
    def avg_words_per_sentence(self):
        ...
    
    @property
    def avg_syllables_per_word(self):
        ...
    
    def __str__(self) -> str:
        ...
    


class Analyzer:
    def __init__(self) -> None:
        ...
    
    def analyze(self, text): # -> AnalyzerStatistics:
        ...
    


