"""
This type stub file was generated by pyright.
"""

from .textstat import TextStatistics, analyzer_instance, textstat

"""
This type stub file was generated by pyright.
"""
__version__ = ...
analyzer: TextStatistics = ...
