"""
This type stub file was generated by pyright.
"""

from scrapy.middleware import MiddlewareManager
from scrapy.utils.conf import build_component_list

"""
Item pipeline

See documentation in docs/item-pipeline.rst
"""
class ItemPipelineManager(MiddlewareManager):
    component_name = ...
    @classmethod
    def _get_mwlist_from_settings(cls, settings):
        ...
    
    def _add_middleware(self, pipe):
        ...
    
    def process_item(self, item, spider):
        ...
    


