"""
This type stub file was generated by pyright.
"""

from typing import Any, List
from twisted.internet.defer import Deferred
from scrapy import Spider
from scrapy.middleware import MiddlewareManager
from scrapy.utils.conf import build_component_list
from scrapy.utils.defer import deferred_f_from_coro_f

"""
Item pipeline

See documentation in docs/item-pipeline.rst
"""
class ItemPipelineManager(MiddlewareManager):
    component_name = ...
    def process_item(self, item: Any, spider: Spider) -> Deferred:
        ...
    


