"""
This type stub file was generated by pyright.
"""

import time as _time
from datetime import datetime, timedelta, tzinfo
from pytz import UTC

'''
Reference tzinfo implementations from the Python docs.
Used for testing against as they are only correct for the years
1987 to 2006. Do not use these for real code.
'''
__all__ = ['FixedOffset', 'LocalTimezone', 'USTimeZone', 'Eastern', 'Central', 'Mountain', 'Pacific', 'UTC']
class FixedOffset(tzinfo):
    """Fixed offset in minutes east from UTC."""
    def __init__(self, offset, name):
        ...
    
    def utcoffset(self, dt):
        ...
    
    def tzname(self, dt):
        ...
    
    def dst(self, dt):
        ...
    


STDOFFSET = timedelta(seconds=- _time.timezone)
if _time.daylight:
    DSTOFFSET = timedelta(seconds=- _time.altzone)
else:
    DSTOFFSET = STDOFFSET
DSTDIFF = DSTOFFSET - STDOFFSET
class LocalTimezone(tzinfo):
    def utcoffset(self, dt):
        ...
    
    def dst(self, dt):
        ...
    
    def tzname(self, dt):
        ...
    
    def _isdst(self, dt):
        ...
    


Local = LocalTimezone()
def first_sunday_on_or_after(dt):
    ...

DSTSTART = datetime(1, 4, 1, 2)
DSTEND = datetime(1, 10, 25, 1)
class USTimeZone(tzinfo):
    def __init__(self, hours, reprname, stdname, dstname):
        self.stdoffset = ...
        self.reprname = ...
        self.stdname = ...
        self.dstname = ...
    
    def __repr__(self):
        ...
    
    def tzname(self, dt):
        ...
    
    def utcoffset(self, dt):
        ...
    
    def dst(self, dt):
        ...
    


Eastern = USTimeZone(- 5, "Eastern", "EST", "EDT")
Central = USTimeZone(- 6, "Central", "CST", "CDT")
Mountain = USTimeZone(- 7, "Mountain", "MST", "MDT")
Pacific = USTimeZone(- 8, "Pacific", "PST", "PDT")
