"""
This type stub file was generated by pyright.
"""

def from_file(filename, config_path=..., requestOptions=...):
    '''
    Detects MIME type of specif'''
    ...

def from_buffer(string, config_path=..., requestOptions=...):
    '''
    Detects MIME type of the bu'''
    ...

