"""
This type stub file was generated by pyright.
"""

def from_file(filename, config_path=..., requestOptions=...):
    '''
    Detects MIME type of specified file
    :param filename: file whose type needs to be detected
    :return: MIME type
    '''
    ...

def from_buffer(string, config_path=..., requestOptions=...):
    '''
    Detects MIME type of the buffered content
    :param string: buffered content whose type needs to be detected
    :return:
    '''
    ...

