"""
This type stub file was generated by pyright.
"""

def from_file(filename, requestOptions=...):
    '''
    Detects language of the fil'''
    ...

def from_buffer(string, requestOptions=...):
    '''
    Detects language of content'''
    ...

