"""
This type stub file was generated by pyright.
"""

def from_file(filename, requestOptions=...):
    '''
    Detects language of the file
    :param filename: path to file whose language needs to be detected
    :return:
    '''
    ...

def from_buffer(string, requestOptions=...):
    '''
    Detects language of content in the buffer
    :param string: buffered data
    :return:
    '''
    ...

