from typing import Any

"""
This type stub file was generated by pyright.
"""

def from_file(
    filename,
    serverEndpoint=...,
    service=...,
    xmlContent=...,
    headers=...,
    config_path=...,
    requestOptions=...,
) -> dict[str, Any]:
    """
    Parses a file for metadata"""
    ...

def from_buffer(
    string,
    serverEndpoint=...,
    xmlContent=...,
    headers=...,
    config_path=...,
    requestOptions=...,
) -> dict[str, Any]:
    """
    Parses the content from buf"""
    ...
