"""
This type stub file was generated by pyright.
"""

def from_file(filename, srcLang, destLang, serverEndpoint=..., requestOptions=...):
    '''
    Traslates the content of source file to destination language
    :param filename: file whose contents needs translation
    :param srcLang: name of language of input file
    :param destLang: name of language of desired language
    :param serverEndpoint: Tika server end point (Optional)
    :return: translated content
    '''
    ...

def from_buffer(string, srcLang, destLang, serverEndpoint=..., requestOptions=...):
    '''
    Translates content from source language to desired destination language
    :param string: input content which needs translation
    :param srcLang: name of language of the input content
    :param destLang: name of the desired language for translation
    :param serverEndpoint:
    :return:
    '''
    ...

def auto_from_file(filename, destLang, serverEndpoint=..., requestOptions=...):
    '''
    Translates contents of a file to desired language by auto detecting the source language
    :param filename: file whose contents needs translation
    :param destLang: name of the desired language for translation
    :param serverEndpoint: Tika server end point (Optional)
    :return:
    '''
    ...

def auto_from_buffer(string, destLang, serverEndpoint=..., requestOptions=...):
    '''
    Translates content to desired language by auto detecting the source language
    :param string: input content which needs translation
    :param destLang: name of the desired language for translation
    :param serverEndpoint: Tika server end point (Optional)
    :return:
    '''
    ...

