"""
This type stub file was generated by pyright.
"""

def from_file(filename, srcLang, destLang, serverEndpoint=..., requestOptions=...):
    '''
    Traslates the content of so'''
    ...

def from_buffer(string, srcLang, destLang, serverEndpoint=..., requestOptions=...):
    '''
    Translates content from sou'''
    ...

def auto_from_file(filename, destLang, serverEndpoint=..., requestOptions=...):
    '''
    Translates contents of a fi'''
    ...

def auto_from_buffer(string, destLang, serverEndpoint=..., requestOptions=...):
    '''
    Translates content to desir'''
    ...

