"""
This type stub file was generated by pyright.
"""

_text_wrapper = ...
def from_file(filename, serverEndpoint=..., requestOptions=...): # -> dict[Unknown, Unknown]:
    '''
    Parse from file
    :param '''
    ...

def from_buffer(string, serverEndpoint=..., requestOptions=...): # -> dict[Unknown, Unknown]:
    '''
    Parse from buffered content'''
    ...

