"""
This type stub file was generated by pyright.
"""

from scrapy.http.response.text import TextResponse
from scrapy.selector.unified import SelectorList

"""
This module implements the HtmlResponse class which adds encoding
discovering through HTML encoding declarations to the TextResponse class.

See documentation in docs/topics/request-response.rst
"""


class HtmlResponse(TextResponse):
    ...

    def css(self, query: str) -> SelectorList:
        ...
