"""
This type stub file was generated by pyright.
"""

from scrapy.http.response.text import TextResponse

"""
This module implements the XmlResponse class which adds encoding
discovering through XML encoding declarations to the TextResponse class.

See documentation in docs/topics/request-response.rst
"""
class XmlResponse(TextResponse):
    ...


