#!/usr/bin/env bash

set -e

OUTPUT_DIR="../glossary-datasets"
SPIDERS=`poetry run scrapy list | grep glossar`

for spider in $SPIDERS; do
    OUTPUT_FILE="${OUTPUT_DIR}/${spider}.json"

    # Skip if the output file already exists
    if [ -f ${OUTPUT_FILE} ]; then
        echo "Skipping ${spider} because it already exists."
        continue
    fi

    echo "Running ${spider}..."
    poetry run scrapy crawl --output ${OUTPUT_FILE} $spider
done
