#!/bin/bash
set -e

#
# submit-coverage
# 
# This script allows Python's coverage.xml file to be located somewhere
# other than the project's root directory. 
#

ID=d97c8df8fdffaae60cb062700f708034c1a6bbd8b7eb87bcb92b8ed1c1d593da


env CC_TEST_REPORTER_ID=$ID bin/cc-test-reporter-darwin format-coverage --input-type coverage.py coverage/coverage.xml
env CC_TEST_REPORTER_ID=$ID bin/cc-test-reporter-darwin upload-coverage
