#!/bin/bash
set -e

#
# submit-coverage
# 
# This script allows Python's coverage.xml file to be located somewhere
# other than the project's root directory. 
#

ID=35924c75e956deb8a730e0a97ac727c2668f664faea35bdf7e4fb0dd4c06c331


env CC_TEST_REPORTER_ID=$ID bin/cc-test-reporter-darwin format-coverage --input-type coverage.py coverage/coverage.xml
env CC_TEST_REPORTER_ID=$ID bin/cc-test-reporter-darwin upload-coverage
