"""
This type stub file was generated by pyright.
"""

import toolz

__all__ = ['merge_with', 'merge']
@toolz.curry
def merge_with(func, d, *dicts, **kwargs): # -> dict[Unknown, Unknown]:
    ...

@toolz.curry
def merge(d, *dicts, **kwargs): # -> dict[Unknown, Unknown]:
    ...

