"""
This type stub file was generated by pyright.
"""

from ..stubs import VCRHTTPConnection, VCRHTTPSConnection

"""Stubs for boto3"""
class VCRRequestsHTTPConnection(VCRHTTPConnection, HTTPConnection):
    _baseclass = HTTPConnection


class VCRRequestsHTTPSConnection(VCRHTTPSConnection, VerifiedHTTPSConnection):
    _baseclass = VerifiedHTTPSConnection
    def __init__(self, *args, **kwargs) -> None:
        ...
    


