"""
This type stub file was generated by pyright.
"""

def get_header(message, name):
    ...

def get_header_items(message): # -> Generator[tuple[Unknown, Unknown], Any, None]:
    ...

def get_headers(message): # -> Generator[tuple[Unknown, Unknown], Any, None]:
    ...

def get_httpmessage(headers): # -> HTTPMessage:
    ...

