"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def get_header(message, name):
    ...

def get_header_items(message):
    ...

def get_headers(message):
    ...

def get_httpmessage(headers):
    ...

