"""
This type stub file was generated by pyright.
"""

from httplib2 import HTTPConnectionWithTimeout, HTTPSConnectionWithTimeout
from ..stubs import VCRHTTPConnection, VCRHTTPSConnection

"""Stubs for httplib2"""
class VCRHTTPConnectionWithTimeout(VCRHTTPConnection, HTTPConnectionWithTimeout):
    _baseclass = HTTPConnectionWithTimeout
    def __init__(self, *args, **kwargs) -> None:
        """I overrode the init because I need to clean kwargs before calling
        HTTPConnection.__init__."""
        ...
    


class VCRHTTPSConnectionWithTimeout(VCRHTTPSConnection, HTTPSConnectionWithTimeout):
    _baseclass = HTTPSConnectionWithTimeout
    def __init__(self, *args, **kwargs) -> None:
        ...
    


