"""
This type stub file was generated by pyright.
"""

"""Stubs for tornado HTTP clients"""
def vcr_fetch_impl(cassette, real_fetch_impl): # -> _Wrapped[(...), Unknown, (self: Unknown, request: Unknown, callback: Unknown), Unknown | None]:
    ...

