"""
This type stub file was generated by pyright.
"""

"""Stubs for tornado HTTP clients"""
def vcr_fetch_impl(cassette, real_fetch_impl): # -> (self: Unknown, request: Unknown, callback: Unknown) -> Unknown:
    ...

