"""
This type stub file was generated by pyright.
"""

import re
import sys
from functools import wraps
from inspect import getmembers
from typing import Dict
from unittest import TestCase
from scrapy.http import Request
from scrapy.utils.python import get_spec
from scrapy.utils.spider import iterate_spider_output

class Contract:
    """ Abstract class for contracts """
    request_cls = ...
    def __init__(self, method, *args) -> None:
        ...
    
    def add_pre_hook(self, request, results):
        ...
    
    def add_post_hook(self, request, results):
        ...
    
    def adjust_request_args(self, args):
        ...
    


class ContractsManager:
    contracts: Dict[str, Contract] = ...
    def __init__(self, contracts) -> None:
        ...
    
    def tested_methods_from_spidercls(self, spidercls): # -> list[Unknown]:
        ...
    
    def extract_contracts(self, method): # -> list[Unknown]:
        ...
    
    def from_spider(self, spider, results): # -> list[Unknown]:
        ...
    
    def from_method(self, method, results): # -> Request | None:
        ...
    


