"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class FalseMeta(type):
    def __bool__(self):
        ...
    
    def __cmp__(self, other):
        ...
    
    __nonzero__ = ...


class UnknownLength(metaclass=FalseMeta):
    ...


class Undefined(metaclass=FalseMeta):
    ...


