"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def progressbar(iterator, min_value=..., max_value=..., widgets=..., prefix=..., suffix=..., **kwargs):
    ...

