"""
This type stub file was generated by pyright.
"""

import inspect
import scrapy
from typing import Callable, List, Optional, Tuple, Type, TypeVar, Union
from w3lib.url import safe_url_string
from scrapy.http.common import obsolete_setter
from scrapy.http.headers import Headers
from scrapy.utils.curl import curl_to_request_kwargs
from scrapy.utils.python import to_bytes
from scrapy.utils.trackref import object_ref
from scrapy.utils.url import escape_ajax

"""
This module implements the Request class which is used to represent HTTP
requests in Scrapy.

See documentation in docs/topics/request-response.rst
"""
RequestTypeVar = TypeVar("RequestTypeVar", bound="Request")
class Request(object_ref):
    """Represents an HTTP request, which is usually generated in a Spider and
    executed by the Downloader, thus generating a :class:`Response`.
    """
    attributes: Tuple[str, ...] = ...
    def __init__(self, url: str, callback: Optional[Callable] = ..., method: str = ..., headers: Optional[dict] = ..., body: Optional[Union[bytes, str]] = ..., cookies: Optional[Union[dict, List[dict]]] = ..., meta: Optional[dict] = ..., encoding: str = ..., priority: int = ..., dont_filter: bool = ..., errback: Optional[Callable] = ..., flags: Optional[List[str]] = ..., cb_kwargs: Optional[dict] = ...) -> None:
        ...
    
    @property
    def cb_kwargs(self) -> dict:
        ...
    
    @property
    def meta(self) -> dict:
        ...
    
    url = ...
    body = ...
    @property
    def encoding(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    def copy(self) -> Request:
        ...
    
    def replace(self, *args, **kwargs) -> Request:
        """Create a new Request with the same attributes except for those given new values"""
        ...
    
    @classmethod
    def from_curl(cls: Type[RequestTypeVar], curl_command: str, ignore_unknown_options: bool = ..., **kwargs) -> RequestTypeVar:
        """Create a Request object from a string containing a `cURL
        <https://curl.haxx.se/>`_ command. It populates the HTTP method, the
        URL, the headers, the cookies and the body. It accepts the same
        arguments as the :class:`Request` class, taking preference and
        overriding the values of the same arguments contained in the cURL
        command.

        Unrecognized options are ignored by default. To raise an error when
        finding unknown options call this method by passing
        ``ignore_unknown_options=False``.

        .. caution:: Using :meth:`from_curl` from :class:`~scrapy.http.Request`
                     subclasses, such as :class:`~scrapy.http.JSONRequest`, or
                     :class:`~scrapy.http.XmlRpcRequest`, as well as having
                     :ref:`downloader middlewares <topics-downloader-middleware>`
                     and
                     :ref:`spider middlewares <topics-spider-middleware>`
                     enabled, such as
                     :class:`~scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware`,
                     :class:`~scrapy.downloadermiddlewares.useragent.UserAgentMiddleware`,
                     or
                     :class:`~scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware`,
                     may modify the :class:`~scrapy.http.Request` object.

        To translate a cURL command into a Scrapy request,
        you may use `curl2scrapy <https://michael-shub.github.io/curl2scrapy/>`_.
        """
        ...
    
    def to_dict(self, *, spider: Optional[scrapy.Spider] = ...) -> dict:
        """Return a dictionary containing the Request's data.

        Use :func:`~scrapy.utils.request.request_from_dict` to convert back into a :class:`~scrapy.Request` object.

        If a spider is given, this method will try to find out the name of the spider methods used as callback
        and errback and include them in the output dict, raising an exception if they cannot be found.
        """
        ...
    


