"""
This type stub file was generated by pyright.
"""

from scrapy.http.request import Request
from typing import Any, Optional

"""
This module implements the FormRequest class which is a more convenient class
(than Request) to generate Requests based on form data.

See documentation in docs/topics/request-response.rst
"""
class FormRequest(Request):
    valid_form_methods = ...
    def __init__(self, *args, **kwargs):
        ...
    
    @classmethod
    def from_response(cls, response, formname: Optional[Any] = ..., formid: Optional[Any] = ..., formnumber=..., formdata: Optional[Any] = ..., clickdata: Optional[Any] = ..., dont_click: bool = ..., formxpath: Optional[Any] = ..., formcss: Optional[Any] = ..., **kwargs):
        ...
    


def _get_form_url(form, url):
    ...

def _urlencode(seq, enc):
    ...

def _get_form(response, formname, formid, formnumber, formxpath):
    """Find the form element """
    ...

def _get_inputs(form, formdata, dont_click, clickdata, response):
    ...

def _value(ele):
    ...

def _select_value(ele, n, v):
    ...

def _get_clickable(clickdata, form):
    """
    Returns the clickable element specified in clickdata,
    if the latter is given. If not, it returns the first
    clickable element found
    """
    ...

