"""
This type stub file was generated by pyright.
"""

from scrapy.http.request import Request
from scrapy.utils.deprecate import create_deprecated_class

"""
This module implements the JsonRequest class which is a more convenient class
(than Request) to generate JSON Requests.

See documentation in docs/topics/request-response.rst
"""
class JsonRequest(Request):
    def __init__(self, *args, **kwargs):
        ...
    
    def replace(self, *args, **kwargs):
        ...
    
    def _dumps(self, data):
        """Convert to JSON """
        ...
    


JSONRequest = create_deprecated_class("JSONRequest", JsonRequest)
