"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple
from scrapy.http.request import Request

"""
This module implements the JsonRequest class which is a more convenient class
(than Request) to generate JSON Requests.

See documentation in docs/topics/request-response.rst
"""
class JsonRequest(Request):
    attributes: Tuple[str, ...] = ...
    def __init__(self, *args, dumps_kwargs: Optional[dict] = ..., **kwargs) -> None:
        ...
    
    @property
    def dumps_kwargs(self) -> dict:
        ...
    
    def replace(self, *args, **kwargs) -> Request:
        ...
    


JSONRequest = ...
