"""
This type stub file was generated by pyright.
"""

from six.moves import xmlrpc_client as xmlrpclib
from scrapy.http.request import Request
from scrapy.utils.python import get_func_args

"""
This module implements the XmlRpcRequest class which is a more convenient class
(that Request) to generate xml-rpc requests.

See documentation in docs/topics/request-response.rst
"""
DUMPS_ARGS = get_func_args(xmlrpclib.dumps)
class XmlRpcRequest(Request):
    def __init__(self, *args, **kwargs):
        ...
    


