"""
This type stub file was generated by pyright.
"""

from typing import Optional
from scrapy.http.request import Request

"""
This module implements the XmlRpcRequest class which is a more convenient class
(that Request) to generate xml-rpc requests.

See documentation in docs/topics/request-response.rst
"""
DUMPS_ARGS = ...
class XmlRpcRequest(Request):
    def __init__(self, *args, encoding: Optional[str] = ..., **kwargs) -> None:
        ...
    


