"""
This type stub file was generated by pyright.
"""

import os
from optparse import OptionGroup
from twisted.python import failure
from scrapy.utils.conf import arglist_to_dict
from scrapy.exceptions import UsageError

"""
Base class for Scrapy commands
"""
class ScrapyCommand(object):
    requires_project = ...
    crawler_process = ...
    default_settings = ...
    exitcode = ...
    def __init__(self):
        self.settings = ...
    
    def set_crawler(self, crawler):
        ...
    
    def syntax(self):
        """
        Command syntax (preferably one-line). Do not include command name.
        """
        ...
    
    def short_desc(self):
        """
        A short description of the command
        """
        ...
    
    def long_desc(self):
        """A long description of the command. Return short description when not
        available. It cannot contain newlines, since contents will be formatted
        by optparser which removes newlines and wraps text.
        """
        ...
    
    def help(self):
        """An extensive help for the command. It will be shown when using the
        "help" command. It can contain newlines, since no post-formatting will
        be applied to its contents.
        """
        ...
    
    def add_options(self, parser):
        """
        Populate option parse with options available for this command
        """
        ...
    
    def process_options(self, args, opts):
        ...
    
    def run(self, args, opts):
        """
        Entry point for running commands
        """
        ...
    


