"""
This type stub file was generated by pyright.
"""

def build_component_list(compdict, custom=..., convert=...): # -> list[Unknown] | tuple[Unknown, ...] | list[Unknown | str]:
    """Compose a component list from a { class: order } dictionary."""
    ...

def arglist_to_dict(arglist): # -> dict[Unknown, Unknown]:
    """Convert a list of arguments like ['arg1=val1', 'arg2=val2', ...] to a
    dict
    """
    ...

def closest_scrapy_cfg(path=..., prevpath=...): # -> str:
    """Return the path to the closest scrapy.cfg file by traversing the current
    directory and its parents
    """
    ...

def init_env(project=..., set_syspath=...): # -> None:
    """Initialize environment to use command-line tool from inside a project
    dir. This sets the Scrapy settings module and modifies the Python path to
    be able to locate the project module.
    """
    ...

def get_config(use_closest=...): # -> ConfigParser:
    """Get Scrapy config file as a ConfigParser"""
    ...

def get_sources(use_closest=...): # -> list[str]:
    ...

def feed_complete_default_values_from_settings(feed, settings):
    ...

def feed_process_params_from_cli(settings, output, output_format=..., overwrite_output=...): # -> dict[Unknown, dict[str, Unknown]] | dict[Unknown, Unknown]:
    """
    Receives feed export params (from the 'crawl' or 'runspider' commands),
    checks for inconsistencies in their quantities and returns a dictionary
    suitable to be used as the FEEDS setting.
    """
    ...

