"""
This type stub file was generated by pyright.
"""

import six
from typing import Any, Optional

if six.PY2:
    ...
else:
    ...
def build_component_list(compdict, custom: Optional[Any] = ..., convert=...):
    """Compose a component list from a { class: order } dictionary."""
    ...

def arglist_to_dict(arglist):
    """Convert a list of arguments like ['arg1=val1', 'arg2=val2', ...] to a
    dict
    """
    ...

def closest_scrapy_cfg(path=..., prevpath: Optional[Any] = ...):
    """Return the path to the closest scrapy.cfg file by traversing the current
    directory and its parents
    """
    ...

def init_env(project=..., set_syspath: bool = ...):
    """Initialize environment to use command-line tool from inside a project
    dir. This sets the Scrapy settings module and modifies the Python path to
    be able to locate the project module.
    """
    ...

def get_config(use_closest: bool = ...):
    """Get Scrapy config file as a ConfigParser"""
    ...

def get_sources(use_closest: bool = ...):
    ...

