"""
This type stub file was generated by pyright.
"""

DEFAULT_PYTHON_SHELLS = ...
def get_shell_embed_func(shells=..., known_shells=...):
    """Return the first acceptable shell-embed function
    from a given list of shell names.
    """
    ...

def start_python_console(namespace=..., banner=..., shells=...):
    """Start Python console bound to the given namespace.
    Readline support and tab completion will be used on Unix, if available.
    """
    ...

