"""
This type stub file was generated by pyright.
"""

from collections import OrderedDict
from typing import Any, Optional

def _embed_ipython_shell(namespace=..., banner=...):
    """Start an IPython Shell"""
    ...

def _embed_bpython_shell(namespace=..., banner=...):
    """Start a bpython shell"""
    ...

def _embed_ptpython_shell(namespace=..., banner=...):
    """Start a ptpython shell"""
    ...

def _embed_standard_shell(namespace=..., banner=...):
    """Start a standard python shell"""
    ...

DEFAULT_PYTHON_SHELLS = OrderedDict([('ptpython', _embed_ptpython_shell), ('ipython', _embed_ipython_shell), ('bpython', _embed_bpython_shell), ('python', _embed_standard_shell)])
def get_shell_embed_func(shells: Optional[Any] = ..., known_shells: Optional[Any] = ...):
    """Return the first acceptable shell-embed function
    from a given list of shell names.
    """
    ...

def start_python_console(namespace: Optional[Any] = ..., banner=..., shells: Optional[Any] = ...):
    """Start Python console bound to the given namespace.
    Readline support and tab completion will be used on Unix, if available.
    """
    ...

