"""
This type stub file was generated by pyright.
"""

def deprecated(use_instead=...): # -> ((*args: Unknown, **kwargs: Unknown) -> Unknown) | ((func: Unknown) -> ((*args: Unknown, **kwargs: Unknown) -> Unknown)):
    """This is a decorator which can be used to mark functions
    as deprecated. It will result in a warning being emitted
    when the function is used."""
    ...

def defers(func): # -> (*a: Unknown, **kw: Unknown) -> Deferred[Unknown]:
    """Decorator to make sure a function always returns a deferred"""
    ...

def inthread(func): # -> (*a: Unknown, **kw: Unknown) -> Deferred[Unknown]:
    """Decorator to call a function in a thread and return a deferred with the
    result
    """
    ...

