"""
This type stub file was generated by pyright.
"""

def deprecated(use_instead=...): # -> _Wrapped[(...), Unknown, (*args: Unknown, **kwargs: Unknown), Unknown] | ((func: Unknown) -> _Wrapped[(...), Unknown, (*args: Unknown, **kwargs: Unknown), Unknown]):
    """This is a decorator which can be used to mark functions
    as deprecated. It will result in a warning being emitted
    when the function is used."""
    ...

def defers(func): # -> _Wrapped[(...), Unknown, (*a: Unknown, **kw: Unknown), Deferred[Unknown]]:
    """Decorator to make sure a function always returns a deferred"""
    ...

def inthread(func): # -> _Wrapped[(...), Unknown, (*a: Unknown, **kw: Unknown), Deferred[Unknown]]:
    """Decorator to call a function in a thread and return a deferred with the
    result
    """
    ...

