"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable
from twisted.internet.defer import Deferred

def deprecated(use_instead: Any = ...) -> Callable:
    """This is a decorator which can be used to mark functions
    as deprecated. It will result in a warning being emitted
    when the function is used."""
    ...

def defers(func: Callable) -> Callable[..., Deferred]:
    """Decorator to make sure a function always returns a deferred"""
    ...

def inthread(func: Callable) -> Callable[..., Deferred]:
    """Decorator to call a function in a thread and return a deferred with the
    result
    """
    ...

