"""
This type stub file was generated by pyright.
"""

from scrapy.utils.decorators import deprecated

@deprecated('GzipFile.read1')
def read1(gzf, size=...):
    ...

def gunzip(data): # -> bytes:
    """Gunzip the given data and return as much data as possible.

    This is resilient to CRC checksum errors.
    """
    ...

def gzip_magic_number(response):
    ...

