"""
This type stub file was generated by pyright.
"""

from typing import Union
from urllib.parse import ParseResult
from weakref import WeakKeyDictionary
from scrapy.http import Request, Response

"""Helper functions for scrapy.http objects (Request, Response)"""
_urlparse_cache: WeakKeyDictionary[Union[Request, Response], ParseResult] = ...
def urlparse_cached(request_or_response: Union[Request, Response]) -> ParseResult:
    """Return urlparse.urlparse caching the result, where the argument can be a
    Request or Response object
    """
    ...

