"""
This type stub file was generated by pyright.
"""

signal_names = ...
def install_shutdown_handlers(function, override_sigint=...): # -> None:
    """Install the given function as a signal handler for all common shutdown
    signals (such as SIGINT, SIGTERM, etc). If override_sigint is ``False`` the
    SIGINT handler won't be install if there is already a handler in place
    (e.g.  Pdb)
    """
    ...

