"""
This type stub file was generated by pyright.
"""

import signal
from types import FrameType
from typing import Any, Callable, Dict, Optional, Union

SignalHandlerT = Union[Callable[[int, Optional[FrameType]], Any], int, signal.Handlers, None]
signal_names: Dict[int, str] = ...
def install_shutdown_handlers(function: SignalHandlerT, override_sigint: bool = ...) -> None:
    """Install the given function as a signal handler for all common shutdown
    signals (such as SIGINT, SIGTERM, etc). If override_sigint is ``False`` the
    SIGINT handler won't be install if there is already a handler in place
    (e.g.  Pdb)
    """
    ...

