"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

"""
Helper functions for serializing (and deserializing) requests.
"""
def request_to_dict(request, spider: Optional[Any] = ...):
    """Convert Request object to a dict.

    If a spider is given, it will try to find out the name of the spider method
    used in the callback and store that as the callback.
    """
    ...

def request_from_dict(d, spider: Optional[Any] = ...):
    """Create Request object from a dict.

    If a spider is given, it will try to resolve the callbacks looking at the
    spider for methods with the same name.
    """
    ...

def _is_private_method(name):
    ...

def _mangle_private_name(obj, func, name):
    ...

def _find_method(obj, func):
    ...

def _get_method(obj, name):
    ...

