"""
This type stub file was generated by pyright.
"""

import weakref

"""
This module provides some useful functions for working with
scrapy.http.Response objects
"""
_baseurl_cache = weakref.WeakKeyDictionary()
def get_base_url(response):
    """Return the base url of the given response, joined with the response url"""
    ...

_metaref_cache = weakref.WeakKeyDictionary()
def get_meta_refresh(response, ignore_tags=...):
    """Parse the http-equiv refrsh parameter from the given response"""
    ...

def response_status_message(status):
    """Return status code plus status text descriptive message
    """
    ...

def response_httprepr(response):
    """Return raw HTTP representation (as bytes) of the given response. This
    is provided only for reference, since it's not the exact stream of bytes
    that was received (that's not exposed by Twisted).
    """
    ...

def open_in_browser(response, _openfunc=...):
    """Open the given response in a local web browser, populating the <base>
    tag for external links to work
    """
    ...

