"""
This type stub file was generated by pyright.
"""

import json
from typing import Any

class ScrapyJSONEncoder(json.JSONEncoder):
    DATE_FORMAT = ...
    TIME_FORMAT = ...
    def default(self, o: Any) -> Any:
        ...
    


class ScrapyJSONDecoder(json.JSONDecoder):
    ...


