"""
This type stub file was generated by pyright.
"""

import json

class ScrapyJSONEncoder(json.JSONEncoder):
    DATE_FORMAT = ...
    TIME_FORMAT = ...
    def default(self, o): # -> list[Unknown] | str | Any:
        ...
    


class ScrapyJSONDecoder(json.JSONDecoder):
    ...


