"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Generator, Iterator, Optional

"""
Module for processing Sitemaps.

Note: The main purpose of this module is to provide support for the
SitemapSpider, its API is subject to change without notice.
"""
class Sitemap:
    """Class to parse Sitemap (type=urlset) and Sitemap Index
    (type=sitemapindex) files"""
    def __init__(self, xmltext: str) -> None:
        ...
    
    def __iter__(self) -> Iterator[Dict[str, Any]]:
        ...
    


def sitemap_urls_from_robots(robots_text: str, base_url: Optional[str] = ...) -> Generator[str, Any, None]:
    """Return an iterator over all sitemap urls contained in the given
    robots.txt file
    """
    ...

