"""
This type stub file was generated by pyright.
"""

"""
Module for processing Sitemaps.

Note: The main purpose of this module is to provide support for the
SitemapSpider, its API is subject to change without notice.
"""
class Sitemap:
    """Class to parse Sitemap (type=urlset) and Sitemap Index
    (type=sitemapindex) files"""
    def __init__(self, xmltext) -> None:
        ...
    
    def __iter__(self): # -> Generator[dict[Unknown, Unknown], Any, None]:
        ...
    


def sitemap_urls_from_robots(robots_text, base_url=...): # -> Generator[Unknown, Any, None]:
    """Return an iterator over all sitemap urls contained in the given
    robots.txt file
    """
    ...

