"""
This type stub file was generated by pyright.
"""

from scrapy.spiders import Spider

logger = ...
def iterate_spider_output(result): # -> AsyncGeneratorType[Any, Any] | Any | list[Unknown] | list[dict[Unknown, Unknown] | Item | str | bytes | Any]:
    ...

def iter_spider_classes(module): # -> Generator[Type[Spider], Any, None]:
    """Return an iterator over all spider classes defined in the given module
    that can be instantiated (i.e. which have name)
    """
    ...

def spidercls_for_request(spider_loader, request, default_spidercls=..., log_none=..., log_multiple=...): # -> None:
    """Return a spider class that handles the given Request.

    This will look for the spiders that can handle the given request (using
    the spider loader) and return a Spider class if (and only if) there is
    only one Spider able to handle the Request.

    If multiple spiders (or no spider) are found, it will return the
    default_spidercls passed. It can optionally log if multiple or no spiders
    are found.
    """
    ...

class DefaultSpider(Spider):
    name = ...


