"""
This type stub file was generated by pyright.
"""

from typing import DefaultDict
from weakref import WeakKeyDictionary

"""
This type stub file was generated by pyright.
"""
NoneType = ...
live_refs: DefaultDict[type, WeakKeyDictionary] = ...
class object_ref:
    """Inherit from this class to a keep a record of live instances"""
    __slots__ = ...
    def __new__(cls, *args, **kwargs):
        ...
    


def format_live_refs(ignore=...):
    """Return a tabular representation of tracked objects"""
    ...

def print_live_refs(*a, **kw):
    """Print tracked objects"""
    ...

def get_oldest(class_name):
    """Get the oldest object for a specific class name"""
    ...

def iter_all(class_name):
    """Iterate over all objects of the same class by its class name"""
    ...

