"""
This type stub file was generated by pyright.
"""

def scrapy_components_versions(): # -> list[tuple[Literal['Scrapy'], str] | tuple[Literal['lxml'], str] | tuple[Literal['libxml2'], str] | tuple[Literal['cssselect'], str] | tuple[Literal['parsel'], str] | tuple[Literal['w3lib'], str] | tuple[Literal['Twisted'], str] | tuple[Literal['Python'], str] | tuple[Literal['pyOpenSSL'], str] | tuple[Literal['cryptography'], str] | tuple[Literal['Platform'], str]]:
    ...

