"""
This type stub file was generated by pyright.
"""

from .itertoolz import *
from .functoolz import *
from .dicttoolz import *
from .recipes import *
from functools import partial, reduce
from . import curried, sandbox
from ._version import get_versions

sorted = ...
map = map
filter = filter
comp = ...
__version__ = get_versions()['version']
